-- Your SQL goes here
CREATE TABLE `files`(
	`id` INTEGER NOT NULL PRIMARY KEY,
	`url` VARCHAR NOT NULL UNIQUE,
	`cache_path` VARCHAR NOT NULL UNIQUE,
	`created` TIMESTAMPTZSQLITE NOT NULL,
	`last_used` TIMESTAMPTZSQLITE NOT NULL,
	`cache_policy` VARCHAR NOT NULL,
	`status` INTEGER NOT NULL,
	`ref_count` INTEGER NOT NULL
);

